apiVersion: v1
kind: Service
metadata:
 name: userexample-service

spec:
 selector:
  app: userexample

 ports:
  - protocol: TCP
    port: 80
    targetPort: 9096
    nodePort: 30011
 type: NodePort
