apiVersion: v1
kind: Pod
metadata:
  name: userexample-pod
spec:
  containers:
  - name: userexample-pod
    image: rajatkumar01/users1.0:latest
    env:
      - name: MYSQL_HOST
        value: "10.103.119.93"
      - name: MYSQL_USER   
        value: "admin"
      - name: MYSQL_PASSWORD
        value: "root"
      - name: MYSQL_DATABASE
        value: "boot_work"

    ports:
      - containerPort: 9096
    imagePullPolicy: Always
    
